### ISSUE TITLE
Import state transition functions

### ISSUE THREAD

**Issue by fpetric** [larics/python-pomdp#3]
Import state transition function.

**Comment by vslosic** [comment]
State transit function is defined with this tag. How should it be imported when I have only one state defined? I remember that we talked about this on our meeting, but still don't completely understand how it should be solved in program because T matrix dimensions are SxS and probabilities in matrix are defined as probabilities of states after desired action that gives as best reward. So is the T matrix for this case [0.5 0.5; 0.5 0.5]? I assumed that <ProbTable> tag tells me the probability of my state, so that 0.5 is actually the probability that my action will make the doors open or not or I got it completely wrong?

`<StateTransitionFunction>
 
<CondProb>
<Var>state_1</Var>
<Parent>action_agent state_0</Parent>
<Parameter type = "TBL">
    <Entry>
        <Instance>listen - -</Instance>
        <ProbTable>identity</ProbTable>
    </Entry>
<Entry>
    <Instance>open-left * *</Instance>
    <ProbTable>0.5</ProbTable>
</Entry>
<Entry>
    <Instance>open-right * *</Instance>
    <ProbTable>0.5</ProbTable>
</Entry>
</Parameter>
</CondProb>
</StateTransitionFunction>
`

**Comment by fpetric** [comment]
Hi!
I have uploaded the file you should work with in the future.

To answer your question, I've said that we will be working with POMDPX files which have the whole transition matrix specified. In such case, the Instance tag of the Parameter is always of the form:

`<Instance> action - - </Instance>`

i.e. ( '<Instance>drink - -</Instance>'), and there should always be N*N elements in the ProbTable tag (N being the number of states).

Similar holds for observations.

**Comment by fpetric** [comment]
Hi, I've seen the commit 1bdd92c, it seems that it works now. We can close the issue now. For future reference, you can close the issue through commit message :). See here:

https://help.github.com/articles/closing-issues-via-commit-messages/
